In [1]:
import pandas as pd

In [2]:
data=pd.read_csv(r"C:\Users\ssss\Downloads\archive (7)\AI_Impact_on_Jobs_2030.csv")
data

,Job_Title,Average_Salary,Years_Experience,Education_Level,AI_Exposure_Index,Tech_Growth_Factor,Automation_Probability_2030,Risk_Category,Skill_1,Skill_2,Skill_3,Skill_4,Skill_5,Skill_6,Skill_7,Skill_8,Skill_9,Skill_10
0,Security Guard,45795,28,Master's,0.18,1.28,0.85,High,0.45,0.10,0.46,0.33,0.14,0.65,0.06,0.72,0.94,0.00
1,Research Scientist,133355,20,PhD,0.62,1.11,0.05,Low,0.02,0.52,0.40,0.05,0.97,0.23,0.09,0.62,0.38,0.98
2,Construction Worker,146216,2,High School,0.86,1.18,0.81,High,0.01,0.94,0.56,0.39,0.02,0.23,0.24,0.68,0.61,0.83
3,Software Engineer,136530,13,PhD,0.39,0.68,0.60,Medium,0.43,0.21,0.57,0.03,0.84,0.45,0.40,0.93,0.73,0.33
4,Financial Analyst,70397,22,High School,0.52,1.46,0.64,Medium,0.75,0.54,0.59,0.97,0.61,0.28,0.30,0.17,0.02,0.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,Doctor,111319,6,Bachelor's,0.24,1.18,0.20,Low,0.73,0.37,0.99,0.07,0.08,0.92,0.65,0.33,0.76,0.45
2996,UX Researcher,44363,29,PhD,0.65,0.74,0.35,Medium,0.23,0.48,0.05,0.88,0.56,0.29,0.69,0.80,0.61,0.20
2997,Data Scientist,61325,23,Master's,0.64,0.94,0.39,Medium,0.28,0.62,0.73,0.21,0.96,0.01,0.70,0.29,0.48,0.57
2998,Graphic Designer,110296,7,PhD,0.95,1.23,0.46,Medium,0.21,0.18,0.14,0.22,0.55,0.68,0.31,0.55,0.34,0.70
2999,Graphic Designer,123909,25,PhD,0.69,0.56,0.49,Medium,0.77,0.54,0.95,0.05,0.29,0.22,0.77,0.52,0.14,0.29

In [3]:
data = data.drop(['Skill_1', 'Skill_2','Skill_3','Skill_4','Skill_5','Skill_6','Skill_7','Skill_8','Skill_9','Skill_10'], axis=1)
data

,Job_Title,Average_Salary,Years_Experience,Education_Level,AI_Exposure_Index,Tech_Growth_Factor,Automation_Probability_2030,Risk_Category
0,Security Guard,45795,28,Master's,0.18,1.28,0.85,High
1,Research Scientist,133355,20,PhD,0.62,1.11,0.05,Low
2,Construction Worker,146216,2,High School,0.86,1.18,0.81,High
3,Software Engineer,136530,13,PhD,0.39,0.68,0.60,Medium
4,Financial Analyst,70397,22,High School,0.52,1.46,0.64,Medium
...,...,...,...,...,...,...,...,...
2995,Doctor,111319,6,Bachelor's,0.24,1.18,0.20,Low
2996,UX Researcher,44363,29,PhD,0.65,0.74,0.35,Medium
2997,Data Scientist,61325,23,Master's,0.64,0.94,0.39,Medium
2998,Graphic Designer,110296,7,PhD,0.95,1.23,0.46,Medium
2999,Graphic Designer,123909,25,PhD,0.69,0.56,0.49,Medium

In [4]:
data.isna().sum()

Job_Title                      0
Average_Salary                 0
Years_Experience               0
Education_Level                0
AI_Exposure_Index              0
Tech_Growth_Factor             0
Automation_Probability_2030    0
Risk_Category                  0
dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
le=LabelEncoder()

In [7]:
data["Job_Title"]=le.fit_transform(data["Job_Title"])
data

,Job_Title,Average_Salary,Years_Experience,Education_Level,AI_Exposure_Index,Tech_Growth_Factor,Automation_Probability_2030,Risk_Category
0,15,45795,28,Master's,0.18,1.28,0.85,High
1,13,133355,20,PhD,0.62,1.11,0.05,Low
2,2,146216,2,High School,0.86,1.18,0.81,High
3,16,136530,13,PhD,0.39,0.68,0.60,Medium
4,6,70397,22,High School,0.52,1.46,0.64,Medium
...,...,...,...,...,...,...,...,...
2995,5,111319,6,Bachelor's,0.24,1.18,0.20,Low
2996,19,44363,29,PhD,0.65,0.74,0.35,Medium
2997,4,61325,23,Master's,0.64,0.94,0.39,Medium
2998,7,110296,7,PhD,0.95,1.23,0.46,Medium
2999,7,123909,25,PhD,0.69,0.56,0.49,Medium

In [8]:
data["Education_Level"]=le.fit_transform(data["Education_Level"])

In [9]:
data["Risk_Category"]=le.fit_transform(data["Risk_Category"])
data

,Job_Title,Average_Salary,Years_Experience,Education_Level,AI_Exposure_Index,Tech_Growth_Factor,Automation_Probability_2030,Risk_Category
0,15,45795,28,2,0.18,1.28,0.85,0
1,13,133355,20,3,0.62,1.11,0.05,1
2,2,146216,2,1,0.86,1.18,0.81,0
3,16,136530,13,3,0.39,0.68,0.60,2
4,6,70397,22,1,0.52,1.46,0.64,2
...,...,...,...,...,...,...,...,...
2995,5,111319,6,0,0.24,1.18,0.20,1
2996,19,44363,29,3,0.65,0.74,0.35,2
2997,4,61325,23,2,0.64,0.94,0.39,2
2998,7,110296,7,3,0.95,1.23,0.46,2
2999,7,123909,25,3,0.69,0.56,0.49,2

In [11]:
X = data.drop("Automation_Probability_2030", axis=1)
y = data["Automation_Probability_2030"]

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [21]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [44]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR

In [45]:
models = {
    "Linear Regression": LinearRegression(),
    
    "Decision Tree": DecisionTreeRegressor(
        max_depth=10,
        min_samples_split=10,
        min_samples_leaf=5,
        random_state=42
    ),
    
    "Random Forest": RandomForestRegressor(
        n_estimators=300,
        max_depth=10,
        min_samples_split=10,
        min_samples_leaf=5,
        random_state=42
    ),
    
    "Gradient Boosting": GradientBoostingRegressor(
        n_estimators=200,
        learning_rate=0.05,
        max_depth=5,
        random_state=42
    ),
    
    "SVR": SVR(
        C=10,
        epsilon=0.1,
        kernel='rbf'
    )
}

In [63]:
results = []

for name, model in models.items():
    
    model.fit(X_train, y_train)
    
    # Predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    # Metrics
    train_r2 = r2_score(y_train, y_train_pred)
    test_r2 = r2_score(y_test, y_test_pred)
    mae = mean_absolute_error(y_test, y_test_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))
    
    results.append([
        name,
        round(train_r2, 4),
        round(test_r2, 4),
        round(mae, 4),
        round(rmse, 4)
    ])

# Create DataFrame
results_df = pd.DataFrame(
    results,
    columns=["Model", "Train R2", "Test R2", "MAE", "RMSE"])
results_df

               Model  Train R2  Test R2     MAE    RMSE
0  Linear Regression    0.1511   0.1914  0.1883  0.2272
1      Decision Tree    0.8895   0.8226  0.0855  0.1064
2      Random Forest    0.9022   0.8636  0.0781  0.0933
3  Gradient Boosting    0.9124   0.8596  0.0790  0.0947
4                SVR    0.8852   0.8230  0.0866  0.1063

In [64]:
model.score(X_test, y_test)

0.8230203862131128

In [65]:
model.score(X_train, y_train)

0.8852267457306731

In [66]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


rf_final = RandomForestRegressor(
    n_estimators=200,        
    max_depth=10,           
    min_samples_split=5,    
    min_samples_leaf=2,     
    random_state=42
)

# Train model
rf_final.fit(X_train, y_train)

RandomForestRegressor(max_depth=10, min_samples_leaf=2, min_samples_split=5,
                      n_estimators=200, random_state=42)

In [67]:
rf_final.score(X_test,y_test)

0.8633044681384006

In [68]:
rf_final.score(X_train,y_train)

0.9118732054688811